name: Mattermost Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Push Details to Mattermost
        run: |
          curl -i -X POST \
          -H 'Content-Type: application/json' \
          -d '{"text": "### 🚀 New Code Push\n**Repository:** ${{ github.repository }}\n**Commit Message:** ${{ github.event.head_commit.message }}\n**Author:** ${{ github.actor }}\n[View Changes](${{ github.event.head_commit.url }})"}' \
          https://happy-stars-lick.loca.lt/hooks/x6q78781stnazbej74paxwoz5h