name: Notify Mattermost on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Mattermost
        run: |
          MESSAGE="🚀 New push to s-deed on branch ${GITHUB_REF_NAME}%0A👤 Author: ${GITHUB_ACTOR}%0A🔗 Commit: https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"

          curl -X POST \
            -H 'Content-Type: application/json' \
            -d "{\"text\":\"$MESSAGE\"}" \
            ${{ secrets.MATTERMOST_WEBHOOK_URL }}